/// @description Base-class for all assertion exceptions.
/// @param {String} [_message] - The exception message.
/// @param {Array<String>} [_stacktrace] - The exception stacktrace. Creates a new one if not provided.
function AssertionError(_message = "", _stacktrace = undefined) : Exception(_message, _stacktrace) constructor {
    if (is_undefined(_stacktrace)) {
        // Erase "self" from the callstack generated by the parent class, `Exception`, by deleting the first item.
        array_delete(stacktrace, 0, 1);
    }
}
